/**
 * Created by tabradford on 7/22/2015.
 */
// I added ui-bootstrap because I did not want to spend too much time making this look pretty...
var app = angular.module('rootControllers', ['ng', 'ngResource','ui.bootstrap']);

// I kept this in the root controller area because it did not seem like it was big enough to
//separate into its own module
app.controller('TabCtrl',function($scope){

    window.location.hash = "#/main";

    $scope.changeHash = function(data) {
        window.location.hash = data;
    };

    $scope.tabs = [
        {title: 'Main', href:"#/main"},
        {title: 'Invoice', href:'#/invoice'},
        {title: 'Calculator', href:'#/calc'},
        {title: 'Users', href:'#/user'},
        {title: 'Slide Show', href:'#/slide'},
        {title: 'GitHub User Info', href:'#/gt_user'},
        {title: 'Flickr', href:'#/flickr'}
    ];
});

// I forget what I was trying to test when I built these but at the time it was important ^_^ I think it had something to do with routing...
app.controller('InvoiceController', ['$scope','$routeParams', function($scope) {
    $scope.test = "InvoiceController is Working. This text was generated by the Angular $scope. Angular and routing are working...";
}]);

app.controller('MainController', ['$scope','$routeParams', function($scope) {
    $scope.test = "MainController is Working. This text was generated by the Angular $scope. Angular and routing are working...";
}]);


/*
* this is a custom filter that has not yet been integrated into the project.
* It should capitalize the first letter of every word
*
app.filter('capitalize', function() {
 return function(input, scope) {
 if (input!=null)
 input = input.toLowerCase();
 return input.substring(0,1).toUpperCase()+input.substring(1);
 }
 });
* */