/**
 * Created by tabradford on 7/22/2015.
 */

var app = angular.module('rootControllers', ['ui.bootstrap']);

app.controller('TabCtrl',function($scope){

    window.location.hash = "#/main";

    $scope.changeHash = function(data) {
        window.location.hash = data;
    };

    $scope.tabs = [
        {title: 'Main', href:"#/main"},
        {title: 'Invoice', href:'#/invoice'},
        {title: 'Calculator', href:'#/calc'},
        {title: 'Users', href:'#/user'},
        {title: 'Slide Show', href:'#/slide'}
    ];
});


app.controller('SlideController', ['$scope','$routeParams', function($scope,$timeout) {

    $scope.count = 0;

    $timeout(function() {
        $scope.count += 1;
        if($scope.count > 10){
            $scope.count = 0;
        }
    }, 3000);


    $scope.pic = ['01','02','03'];
}]);

app.service('SlideService', function(){

    //unique number generator
    var mixedList= [];//sequential numbers between 1 and 10 that will be shuffled
    var randList = [];// will be random numbers between 0 and 9
    var temp = 0;//holds one var at a time.
    var stringNum = {};
    // populates my mixedList
    function loadList(){
        // loads both of my arrays
        for(var i = 0; i < 10; i++){
            mixedList.push(i + 1);
            randList.push(Math.floor((Math.random() * 10)));
        }

        //shuffle mixedList using the randList
        for(var i = 0; i < 10; i++){
            temp = mixedList[i];
            mixedList[i] = mixedList[randList[i]];
            mixedList[randList[i]] = temp;
        }
    }

    function getRand(){
        return mixedList;
    }

    function getString(){

        stringNum.push("0"+mixedList);
    }

    function mixer() {
        // empty all vars in order to get a new set every time
        mixedList= [];
        randList = [];
        temp = 0;
        //populates my mixedList
        loadList();
    }

    return {
        mixer: mixer,
        getList: getRand
    }

});

app.controller('InvoiceController', ['$scope','$routeParams', function($scope) {
    $scope.test = "InvoiceController is Working. This text was generated by the Angular $scope. Angular and routing are working...";
}]);

app.controller('MainController', ['$scope','$routeParams', function($scope) {
    $scope.test = "MainController is Working. This text was generated by the Angular $scope. Angular and routing are working...";
}]);
