/**
 * Created by tabradford on 7/22/2015.
 */

var app = angular.module('rootControllers', ['ui.bootstrap']);

app.controller('TabCtrl',function($scope){

    window.location.hash = "#/main";

    $scope.changeHash = function(data) {
        window.location.hash = data;
    };

    $scope.tabs = [
        {title: 'Main', href:"#/main"},
        {title: 'Invoice', href:'#/invoice'},
        {title: 'Calculator', href:'#/calc'},
        {title: 'Slide Show', href:'#/slide'}
    ];
});

app.controller('SlideController', ['$scope','$routeParams', function($scope) {
    $scope.test = "Slide show made by tim!";
    $scope.user = {
        name: 'Luke Skywalker',
        address:{
            street: 'Hidden Forest',
            city: 'Secret Rebel Base',
            planet: 'Yavin 4'
        },
        friends: [
            'Han',
            'Leia',
            'Chewbacca'
        ]
    }
}]);

app.directive('tbSlideForMe', function(){
   return {
        templateUrl: "templates/slideTemp.html",
        restrict: "E", //"A" = attribute, "E" = element, "C" = class, "M" = comments you can use more then one at the same time...
        replace: true// this will replace the custom div tag for compatibility. the only thing is you need to wrap you html file in a div if you do this.
   }
});

app.controller('InvoiceController', ['$scope','$routeParams', function($scope) {
    $scope.test = "InvoiceController is Working. This text was generated by the Angular $scope. Angular and routing are working...";
}]);

app.controller('MainController', ['$scope','$routeParams', function($scope) {
    $scope.test = "MainController is Working. This text was generated by the Angular $scope. Angular and routing are working...";
}]);
