/**
 * Created by tabradford on 7/27/2015.
 */
app.controller('CalcController', ['$scope','Calc','$routeParams', function($scope,Calc) {
    //$scope.test = "CalcController is Working. This text was generated by the Angular $scope. Angular and routing are working...";

    //Functions
    $scope.operationPress = function(theOperation, new_swtc) {
        $scope.result = Calc.operationPress(theOperation, new_swtc); //returns total
        $scope.calcNumber = Calc.getCalcNumber();

    };

    $scope.numberPress = function(theNumber) {
        $scope.calcNumber = Calc.numberPress(theNumber);//returns calcNumber

    };

    $scope.clearPress = function() {
        Calc.clearPress();
        $scope.result = 0;
        $scope.calcNumber = "";
    };

    //Variables
    $scope.calcNumber = Calc.getCalcNumber();
    $scope.result = Calc.getTotal();

}]);